"""add game config field

Revision ID: 1b6154ba883e
Revises: b34d93bf8a1f
Create Date: 2025-06-14 09:44:06.501164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6154ba883e'
down_revision: Union[str, None] = 'b34d93bf8a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_targets', sa.Column('game_config', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_targets', 'game_config')
    # ### end Alembic commands ###
