"""initial baseline

Revision ID: 58e32512480d
Revises: 
Create Date: 2025-04-10 16:27:16.667238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e32512480d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itch_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('butler_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_dir', sa.String(), nullable=False),
    sa.Column('archive_directory', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steam_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('steamcmd_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('build_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('target_branch', sa.String(), nullable=False),
    sa.Column('build_type', sa.Enum('dev', 'prod', name='buildtypeenum'), nullable=False),
    sa.Column('target_platform', sa.Enum('win_64', 'win_32', 'mac_os', name='buildtargetplatformenum'), nullable=False),
    sa.Column('optimize_for_steam', sa.Boolean(), nullable=False),
    sa.Column('auto_sync_branch', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publish_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_type', sa.Enum('itch', 'steam', name='storeenum'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itch_publish_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itch_user_game_id', sa.String(), nullable=False),
    sa.Column('itch_channel_name', sa.String(), nullable=False),
    sa.Column('itch_config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['publish_profile.id'], ),
    sa.ForeignKeyConstraint(['itch_config_id'], ['itch_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steam_publish_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('depots', sa.JSON(), nullable=False),
    sa.Column('steam_config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['publish_profile.id'], ),
    sa.ForeignKeyConstraint(['steam_config_id'], ['steam_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vcs_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcs_type', sa.Enum('perforce', 'git', name='vcstypeenum'), nullable=False),
    sa.Column('build_target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['build_target_id'], ['build_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gitconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remote_url', sa.String(), nullable=False),
    sa.Column('ssh_key_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['vcs_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('p4config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('server_address', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['vcs_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('p4config')
    op.drop_table('gitconfig')
    op.drop_table('vcs_configs')
    op.drop_table('steam_publish_profile')
    op.drop_table('itch_publish_profile')
    op.drop_table('publish_profile')
    op.drop_table('build_targets')
    op.drop_table('steam_config')
    op.drop_table('project')
    op.drop_table('itch_config')
    # ### end Alembic commands ###
