"""add maps json field

Revision ID: 9ee7c83a755f
Revises: d80d983d9759
Create Date: 2025-06-14 21:46:44.956919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee7c83a755f'
down_revision: Union[str, None] = 'd80d983d9759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_targets', sa.Column('maps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_targets', 'maps')
    # ### end Alembic commands ###
