"""itch models

Revision ID: a5f0ec84c4d2
Revises: d64c311412a5
Create Date: 2025-04-09 13:35:21.054651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f0ec84c4d2'
down_revision: Union[str, None] = 'd64c311412a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itch_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('itch_user_game_id', sa.String(), nullable=True),
    sa.Column('butler_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itch_user_game_id')
    )
    op.drop_column('steam_config', 'builder_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steam_config', sa.Column('builder_path', sa.VARCHAR(), nullable=True))
    op.drop_table('itch_config')
    # ### end Alembic commands ###
