"""add steam playtest fields

Revision ID: b34d93bf8a1f
Revises: dca64d720639
Create Date: 2025-04-28 10:34:58.607967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34d93bf8a1f'
down_revision: Union[str, None] = 'dca64d720639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steam_publish_profile', sa.Column('playtest_app_id', sa.Integer(), nullable=True))
    op.add_column('steam_publish_profile', sa.Column('playtest_description', sa.String(), nullable=True))
    op.add_column('steam_publish_profile', sa.Column('playtest_depots', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steam_publish_profile', 'playtest_depots')
    op.drop_column('steam_publish_profile', 'playtest_description')
    op.drop_column('steam_publish_profile', 'playtest_app_id')
    # ### end Alembic commands ###
