"""replace game config with target

Revision ID: d80d983d9759
Revises: 1b6154ba883e
Create Date: 2025-06-14 21:18:29.428423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80d983d9759'
down_revision: Union[str, None] = '1b6154ba883e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_targets', sa.Column('target', sa.String(), nullable=True))
    op.drop_column('build_targets', 'game_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_targets', sa.Column('game_config', sa.VARCHAR(), nullable=True))
    op.drop_column('build_targets', 'target')
    # ### end Alembic commands ###
