"""add engine_path to build target

Revision ID: dca64d720639
Revises: 58e32512480d
Create Date: 2025-04-12 08:59:06.389609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca64d720639'
down_revision: Union[str, None] = '58e32512480d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_targets', sa.Column('unreal_engine_base_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_targets', 'unreal_engine_base_path')
    # ### end Alembic commands ###
