"""add archive dir to build_target

Revision ID: ea01e881bea9
Revises: f0c70761b718
Create Date: 2025-04-07 19:03:58.727607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea01e881bea9'
down_revision: Union[str, None] = 'f0c70761b718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_targets', sa.Column('archive_directory', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_targets', 'archive_directory')
    # ### end Alembic commands ###
