"""initial migration

Revision ID: f0c70761b718
Revises: 
Create Date: 2025-04-07 14:47:12.354794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c70761b718'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_dir', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('build_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('target_branch', sa.String(), nullable=False),
    sa.Column('build_type', sa.Enum('dev', 'prod', name='buildtypeenum'), nullable=False),
    sa.Column('target_platform', sa.Enum('win_64', 'win_32', 'mac_os', name='buildtargetplatformenum'), nullable=False),
    sa.Column('optimize_for_steam', sa.Boolean(), nullable=False),
    sa.Column('auto_sync_branch', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vcs_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vcs_type', sa.Enum('perforce', 'git', name='vcstypeenum'), nullable=False),
    sa.Column('build_target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['build_target_id'], ['build_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gitconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remote_url', sa.String(), nullable=False),
    sa.Column('ssh_key_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['vcs_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('p4config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('server_address', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['vcs_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('p4config')
    op.drop_table('gitconfig')
    op.drop_table('vcs_configs')
    op.drop_table('build_targets')
    op.drop_table('project')
    # ### end Alembic commands ###
