title: Build Bridge
description: A GUI utility to organize, build, and launch your Unreal Engine projects on Itch.io and Steam.
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

url: "https://collederas.github.io" 
baseurl: "/build-bridge"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: false
      toc: true
      toc_sticky: true

footer_scripts:
  - /assets/js/external-links.js