name: Build and Deploy to Itch.io

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to simulate (e.g., v0.1.1-test)'
        required: true
        default: 'v0.1.1-test'
      deploy_to_itch:
        description: 'Deploy to itch.io? (true/false)'
        type: boolean
        default: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller `
            --noconsole `
            --icon=build_bridge\icons\buildbridge.ico `
            --add-data "build_bridge\icons\buildbridge.ico;build_bridge\icons/" `
            --add-data "build_bridge/core/publisher/steam/app_build_template.vdf;build_bridge/core/publisher/steam/" `
            --add-data "alembic:alembic" `
            --add-data "alembic.ini:." `
            --paths .venv\Lib\site-packages `
            --name BuildBridge `
            app.py
            
      - name: Install Butler
        run: |
          choco install butler
        shell: powershell
        if: ${{ github.event.inputs.deploy_to_itch == 'true' || github.event_name != 'workflow_dispatch' }}

      - name: Deploy to Itch.io
        if: ${{ github.event.inputs.deploy_to_itch == 'true' || github.event_name != 'workflow_dispatch' }}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          set TAG=${{ github.event.inputs.tag_name || github.ref_name }}
          butler push .\dist\BuildBridge collederas/build-bridge:windows --userversion %TAG%
        shell: cmd