name: Build and Deploy to Itch.io

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to simulate (e.g., v0.1.1-test)'
        required: true
        default: 'v0.1.1-test'
      deploy_to_itch:
        description: 'Deploy to itch.io? (true/false)'
        type: boolean
        default: false

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root --with dev
        shell: bash

      - name: Build with PyInstaller
        run: |
          poetry run pyinstaller --noconsole \
            --icon=build_bridge/icons/buildbridge.ico \
            --add-data "build_bridge/icons:icons" \
            --name BuildBridge \
            --exclude-module tkinter \
            --exclude-module numpy \
            --exclude-module scipy \
            --exclude-module pandas \
            --exclude-module matplotlib \
            ./app.py
        shell: bash

      - name: Zip the build
        run: |
          $tag = "${{ github.event.inputs.tag_name || github.ref_name }}"
          Compress-Archive -Path .\dist\BuildBridge\* -DestinationPath BuildBridge-$tag.zip
        shell: bash

# Only run following 2 if an actual tag has been pushed or if deployment has been requested specifically
      - name: Install Butler
        run: |
          choco install butler
        shell: powershell
        if: ${{ github.event.inputs.deploy_to_itch == 'true' || github.event_name != 'workflow_dispatch' }}

      - name: Deploy to Itch.io
        if: ${{ github.event.inputs.deploy_to_itch == 'true' || github.event_name != 'workflow_dispatch' }}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          set TAG=${{ github.event.inputs.tag_name || github.ref_name }}
          butler push BuildBridge-%TAG%.zip collederas/build-bridge:windows --userversion %TAG%
        shell: cmd